# Game settings
WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 1000


# Tank settings
TANK_SPEED = 4
TANK_ROTATION_SPEED = 4
TANK_SHOOTER_ROTATION_SPEED = 4


# Bullet settings
BULLET_COOLDOWN = 10
BULLET_LIFETIME = 50
BULLET_SPEED = 10

# Wall settings
WALL_COLOR = (0, 0, 0)
WALL_THICKNESS = 10
